### ISSUE TITLE
Request for info

### ISSUE THREAD

**Issue by caclark** [BertoldVdb/ZoneDetect#1]
Could you tell me the difference between the ...16.bin and ...21.bin libraries?
And how should I interpret the `safezone` parameter?

Thanks

Colin Clark

**Comment by BertoldVdb** [comment]
Hello,

The number indicates the resolution. The 21 file has a higher resolution for storing the borders, but it is larger. The 16 file has a longitude resolution of 0.0055 degrees (~0.5km) and the 21 file has 0.00017 degrees (~20m). 

The safe zone result indicates how close you are to the nearest border (flat earth model using lat and lon as x and y), so you can know when to do a new lookup. If you don't need it you can ignore it, in this case you can pass a NULL parameter to save the calculation effort.

Sincerely,
Bertold Van den Bergh

**Comment by caclark** [comment]
Thanks for the data.

I intend to use ZoneDetect in the image viewer project, Geeqie:
https://github.com/BestImageViewer/geeqie
Could you tell me if I need to include a copywrite notice for the underlying data you use to create the .bin files?

**Comment by BertoldVdb-byteflies** [comment]
Hi,

It depends. The country data is from NaturalEarth and does not need any credit. The timezone+country data is from OpenStreetMap and its license is here: https://github.com/BertoldVdb/ZoneDetect/blob/master/database/timezone_DATA_LICENSE

There is a copyright notice in the library files, you can get it using ZDGetNotice

Sincerely,
Bertold Van den Bergh

**Comment by BertoldVdb** [comment]
Hi,

It depends. The country data is from NaturalEarth and does not need any credit. The timezone+country data is from OpenStreetMap and its license is here: https://github.com/BertoldVdb/ZoneDetect/blob/master/database/timezone_DATA_LICENSE

There is a copyright notice in the library files, you can get it using ZDGetNotice

Sincerely,
Bertold Van den Bergh
