### ISSUE TITLE
Compability with Mingw-w64

### ISSUE THREAD

**Issue by zedxxx** [BertoldVdb/ZoneDetect#11]
Mingw-w64 has define `__MINGW32__`  to detect it and I successfully compile library with minor modifications:
```
- #if defined(_MSC_VER)
+ #if defined(_MSC_VER) || defined(__MINGW32__)
```
in all cases except using `__try` / `__except` Microsoft extensions. 

Is it safe to use lib without this error handling? Do you know how your library can be compiled with mingw-w64 in the proper way?

**Comment by BertoldVdb** [comment]
It should be safe to use it without the try/except. The library should not attempt to access the mapped file out of bounds. This was tested by fuzzing.

That said, I only used this on embedded linux platforms.

**Comment by zedxxx** [comment]
See https://github.com/BertoldVdb/ZoneDetect/pull/12

**Comment by BertoldVdb** [comment]
Thank you.
