### ISSUE TITLE
Initialize local variable, fixes macOS compilation

### ISSUE THREAD

**Issue by jad6** [BertoldVdb/ZoneDetect#16]
Line 391 in `zondetect.c` (as of db66d4475abcec5e1f1dfed442c3115bc1a8b5a2) does not initialize `point`:

```
    if(reader->library->version == 1) {
        uint64_t point;

        if(!reader->referenceDirection) {
```

Compiling with Xcode 11.1 and default clang settings fails. Initializing it 0 does the trick.

P.S. I cannot contribute to OSS so unfortunately no PR but this should be a simple fix :)

**Comment by BertoldVdb** [comment]
Thank you. Done.
