### ISSUE TITLE
license

### ISSUE THREAD

**Issue by miseryofdevice** [BertoldVdb/ZoneDetect#18]
Hi there,

maybe a short thing, but: Could you add some license (MIT or so ) :+1: :smile: to this?

**Comment by BertoldVdb** [comment]
Hello,

There is in the files as comment (BSD). I will add a global license file tonight.

Sincerely,
Bertold

**Comment by miseryofdevice** [comment]
Great! Thanks.

**Comment by BertoldVdb** [comment]
Done.
