### ISSUE TITLE
Can it work with Android ？

### ISSUE THREAD

**Issue by CronZhu** [BertoldVdb/ZoneDetect#25]

**Comment by BertoldVdb** [comment]
I didn't try it, but I guess so. Compile it with the NDK.

If you don't want to include the big database, you can also use the online service: https://timezone.bertold.org/timezone?lat=51&lon=5

**Comment by niedzi** [comment]
It is possible actually. I've just used NDK to build that and wrote JNI wrapper to access C code from activity. I am able to grab country code based on long and latt using db file stored in sdcard.

**Comment by BertoldVdb** [comment]
@niedzi 

Great. Thanks for letting us know!

**Comment by seesoe** [comment]
@niedzi would you be able to share with us an example of how you achieved this?
