### ISSUE TITLE
Is there an estimate of memory usage when running?

### ISSUE THREAD

**Issue by whc2001** [BertoldVdb/ZoneDetect#27]
I am trying to port this library to embedded device (low RAM, no mmap, data only read from external SPI flash memory). Before actually got hand on that I wonder if there is a rough value of memory consumption so I will be able to determine whether it actually can run on my microcontroller.

**Comment by BertoldVdb** [comment]
Hi,

The library itself should not use a lot of RAM, certainly less than a few 100 bytes. The current code uses mmap as you saw, you will need to replace all access to 'library->mapping' with a function reading from your SPI flash. It would of course be best if you can cleanly integrate non-mmap access to the db, then we can merge this functionality.

The low accuracy database is 1MB (out_v1/timezone16.bin, ~0.5km) and the higher accuracy one 4MB (out_v1/timezone21.bin, ~20m). If this is still too much you can generate your own database with even less accuracy.

The code supports two database formats. To save code space in your micro-controller you could remove the support for version == 0, but the gain will not be big.

Sincerely,
Bertold

**Comment by whc2001** [comment]
Thanks for let me knowing, but I figured out later that I don't really need timezone data and I was being lazy, so :) but still thanks for the help and bringing such a useful library!
