### ISSUE TITLE
How to get ...bin files

### ISSUE THREAD

**Issue by iknow34languages** [BertoldVdb/ZoneDetect#3]
@BertoldVdb 

Can you tell what contents is contained in the bin files?

and how to get the bin files?

i see that  Jave code don't need the bin files.

Thanks!

**Comment by BertoldVdb** [comment]
The bin files contain the database used to obtain the results. It is created from a shapefile. I am planning to upload the tool to generate them but it needs cleanup and I have little time at the moment.

**Comment by iknow34languages** [comment]
@BertoldVdb 
i compose a similar bin from json file;
https://github.com/iknow34languages/Problems/tree/questions/question_3

change the code to test :

> for(j=0; j<library->numFields; j++) 

to

> ] for(j=0; j<1; j++)

**Comment by iknow34languages** [comment]
@BertoldVdb 
i compose a similar bin file from geo json ;
https://github.com/iknow34languages/Problems/tree/questions/question_3
need change code:

> for(j=0; j<library->numFields; j++) 

to

>  for(j=0; j<1; j++)
