### ISSUE TITLE
Database file format ?

### ISSUE THREAD

**Issue by andreas-kupries** [BertoldVdb/ZoneDetect#31]
Thank you for such a useful library.

Going over the available files I can't seem to find a specification of the file format used by the `.bin` files.
Does such exist ?
If yes, could it be made available ?

**Comment by prashantpsg** [comment]
Hi,
I understood how to run this  by giving latitude and longitude but i have a doubt . how and where to get this timezone21.bin ? How to generate this file timezone21.bin  ?
