### ISSUE TITLE
how and where to get this timezone21.bin file

### ISSUE THREAD

**Issue by prashantpsg** [BertoldVdb/ZoneDetect#33]
Hi,
I understood how to run this by giving latitude and longitude but i have a doubt . how and where to get this timezone21.bin ? How to generate this file timezone21.bin ?

**Comment by BertoldVdb** [comment]
Hello,

You can download the database (including timezone21.bin) here:  https://cdn.bertold.org/zonedetect/db/db.zip

The script to generate it can be found here: https://github.com/BertoldVdb/ZoneDetect/tree/master/database

Sincerely,
Bertold
