### ISSUE TITLE
Why library is stripped during install stage

### ISSUE THREAD

**Issue by sathishthangaraj** [BertoldVdb/ZoneDetect#38]
https://github.com/BertoldVdb/ZoneDetect/blob/0e7c2729c1bd54deea8121d830745243a1970df3/library/Makefile#L75

Usually in yocto libraries will be stripped only during packaging, libraries under image directory are non stripped versions.

May i know the reason why we strip the library during installation? this will limit the debugging of the library right?

**Comment by BertoldVdb** [comment]
If you don't want to strip it, you can set the STRIP environment variable to an empty string in your Bitbake recipe. Yocto will then indeed strip it itself depending on your configuration during the packaging step.
