### ISSUE TITLE
Which algorithm used in ZDPointInPolygon?

### ISSUE THREAD

**Issue by iknow34languages** [BertoldVdb/ZoneDetect#4]
@BertoldVdb Can you help to explain which algorithm in ZDPointInPolygon function?

i find that it can not give correct Time zone id when give  egdes posistions?

it caused by algorithm or database ?

Thanks

**Comment by BertoldVdb** [comment]
Hello,

I am at work now and will reply in more detail later. Could you give an example of a set of coordinates that gives the wrong result?

Sincerely,
Bertold

**Comment by iknow34languages** [comment]
@BertoldVdb 

There is a test position;

26 | -9 | Africa/El_Aaiun

it is not the same with the same results coming from JAVA code.
25|-9 Africa/Nouakchott 

Thanks

**Comment by BertoldVdb** [comment]
Hello,

I checked that 26, -9 is in Mauritania. According to this I think
Africa/Nouakchott
is the right result.

Could you refer me to the other library you use so I can compare it? My
data comes from openstreetmap.

Sincerely,
Bertold

**Comment by iknow34languages** [comment]
@BertoldVdb Thie project :

**Comment by iknow34languages** [comment]
@BertoldVdb it seems i make a mistake !!! the right one comes from your project.
i ll take more position to test with your code.

Thanks!

**Comment by BertoldVdb** [comment]
No problem, thank you!
