### ISSUE TITLE
Safezone details

### ISSUE THREAD

**Issue by timothy-godfrey** [BertoldVdb/ZoneDetect#41]
Hi! Regarding the Safezone set by ZDLookup, in  #1 you say 

`The safe zone result indicates how close you are to the nearest border (flat earth model using lat and lon as x and y), so you can know when to do a new lookup.`

What are the units of the Safezone? Meters? Kilometers?

When you say, "so you can know when to do a new lookup," do you mean that I should do a new lookup if my location has changed by more than the distance reported in Safezone?

Thanks!

**Comment by BertoldVdb** [comment]
Hi,

The safe zone is simply calculated as the sqrt(x^2+y^2) where x is latitude difference and y is longitude difference to the nearest border segment. The unit is thus not standard, but you can check when the result could potentially have changed.

Sincerely,
Bertold
