### ISSUE TITLE
get Time Zone GMT offset

### ISSUE THREAD

**Issue by jialinxie** [BertoldVdb/ZoneDetect#8]
hi, is there a way to get GMT offset (-1, +14, 0, ...) from Lat Long Coordinates/ or timeZone name?
like this [issue](https://github.com/MrMinimal64/timezonefinder/issues/51) on[timezonefinder](https://github.com/MrMinimal64/timezonefinder)

**Comment by dynaperapp** [comment]
Without timestamp the information you want is not correct cause GMT offset changes throughout the year (summer time/winter time).

**Comment by BertoldVdb** [comment]
You need to know the time to be able to do this, since some zones have a varying offset during the year (DST). You can use any timezone library with the output of this program to obtain it.
